# Server configuration
server.port=8080

# Spring configuration
spring.application.name=web-api

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Micrometer OTLP Registry Configuration
# Directs metric exports to the OpenTelemetry Collector's HTTP endpoint
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
management.otlp.metrics.export.step=5s
management.opentelemetry.resource-attributes.service.name=web-api
management.opentelemetry.resource-attributes.environment=development
